# https://docs.gradle.org/current/userguide/version_catalogs.html#sec:version-catalog-declaration
[versions]
assertj = "3.27.7"
junit = "6.0.2"
version-catalog-update = "1.0.1"

[libraries]
assertj = { module = "org.assertj:assertj-bom", version.ref = "assertj" }
junit = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
# https://github.com/littlerobots/version-catalog-update-plugin
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
