# https://docs.gradle.org/current/userguide/version_catalogs.html#sec:version-catalog-declaration
[versions]
assertj = "3.27.6"
assertj-vavr = "0.4.3"
junit = "6.0.2"
vavr = "0.11.0"
version-catalog-update = "1.0.1"

[libraries]
assertj = { module = "org.assertj:assertj-bom", version.ref = "assertj" }
assertj-vavr = { module = "org.assertj:assertj-vavr", version.ref = "assertj-vavr" }
junit = { module = "org.junit:junit-bom", version.ref = "junit" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }

[plugins]
# https://github.com/littlerobots/version-catalog-update-plugin
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
